// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretClaim) DeepCopyInto(out *SecretClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretClaim.
func (in *SecretClaim) DeepCopy() *SecretClaim {
	if in == nil {
		return nil
	}
	out := new(SecretClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretClaimList) DeepCopyInto(out *SecretClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretClaimList.
func (in *SecretClaimList) DeepCopy() *SecretClaimList {
	if in == nil {
		return nil
	}
	out := new(SecretClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretClaimSpec) DeepCopyInto(out *SecretClaimSpec) {
	*out = *in
	if in.TokenFields != nil {
		in, out := &in.TokenFields, &out.TokenFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FixedFields != nil {
		in, out := &in.FixedFields, &out.FixedFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.X509Claim != nil {
		in, out := &in.X509Claim, &out.X509Claim
		*out = new(X509Claim)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretClaimSpec.
func (in *SecretClaimSpec) DeepCopy() *SecretClaimSpec {
	if in == nil {
		return nil
	}
	out := new(SecretClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretClaimStatus) DeepCopyInto(out *SecretClaimStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretClaimStatus.
func (in *SecretClaimStatus) DeepCopy() *SecretClaimStatus {
	if in == nil {
		return nil
	}
	out := new(SecretClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *X509Claim) DeepCopyInto(out *X509Claim) {
	*out = *in
	if in.ServiceNames != nil {
		in, out := &in.ServiceNames, &out.ServiceNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraNames != nil {
		in, out := &in.ExtraNames, &out.ExtraNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new X509Claim.
func (in *X509Claim) DeepCopy() *X509Claim {
	if in == nil {
		return nil
	}
	out := new(X509Claim)
	in.DeepCopyInto(out)
	return out
}
